spring.application.name=FirstAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/first_api
spring.datasource.username=postgres
spring.datasource.password=ulkf
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true